apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  ingress:
    enabled: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jeager-dashboard
spec:
  rules:
    - host: jaeger.localhost
      http:
        paths:
          - backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
            pathType: ImplementationSpecific
