apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-deployment
  labels:
    app: company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
      annotations:
        "resource.opentelemetry.io/service.name": "company-service"
        "instrumentation.opentelemetry.io/inject-java": "true"
    spec:
      containers:
        - name: company
          image: ghcr.io/andreasgerner/distributed-tracing/sample-company:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PAYMENT_URL
              value: "http://payment-service:8080"
            - name: DB_URL
              value: jdbc:sqlserver://host.docker.internal:10001;encrypt=true;trustServerCertificate=true;username=sa;password=yourStrongPassword1!;
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
  labels:
    app: company
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: company
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: company-ingress
spec:
  rules:
    - host: company.localhost
      http:
        paths:
          - backend:
              service:
                name: company-service
                port:
                  name: http
            pathType: ImplementationSpecific
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        "resource.opentelemetry.io/service.name": "payment-service"
        "instrumentation.opentelemetry.io/inject-java": "true"
    spec:
      containers:
        - name: payment
          image: ghcr.io/andreasgerner/distributed-tracing/sample-payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:sqlserver://host.docker.internal:10002;encrypt=true;trustServerCertificate=true;username=sa;password=yourStrongPassword1!;
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: payment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-ingress
spec:
  rules:
    - host: payment.localhost
      http:
        paths:
          - backend:
              service:
                name: payment-service
                port:
                  name: http
            pathType: ImplementationSpecific
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/andreasgerner/distributed-tracing/sample-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
spec:
  rules:
    - host: web.localhost
      http:
        paths:
          - backend:
              service:
                name: web-service
                port:
                  name: http
            pathType: ImplementationSpecific
