tracing:
  otlp:
    enabled: true
    http:
      enabled: true
      endpoint: http://opentelemetry-collector-collector.otel.svc.cluster.local:4318

metrics:
  prometheus: null

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.localhost`)
    entryPoints: [ "web" ]
