apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  ingress:
    ingressClassName: openshift-default
    tls:
      - hosts:
          - tracing-otel-collector.apps.ocp-test.cloud.nuernberger.net
        secretName: nv-default-cert
    hostname: tracing-otel-collector.apps.ocp-test.cloud.nuernberger.net
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      otlp:
        endpoint: "http://jaeger-collector:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
