global:
  imageRegistry: artifactory:5000

provisionDataStore:
  cassandra: false

storage:
  type: elasticsearch
  elasticsearch:
    host: elasticsearch
    port: 9200
    scheme: http
    user: elastic
    password: j43g3r2024

query:
  service:
    targetPort: 16686
  ingress:
    enabled: true
    ingressClassName: openshift-default
    tls:
      - hosts:
          - tracing-jaeger.apps.ocp-test.cloud.nuernberger.net
        secretName: nv-default-cert
    hosts:
      - tracing-jaeger.apps.ocp-test.cloud.nuernberger.net

collector:
  service:
    otlp:
      grpc:
        name: otlp-grpc
        port: 4317
      http:
        name: otlp-http
        port: 4138
