apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}-company
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app: company
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
      app: company
  template:
    metadata:
      labels:
        {{- include "sample-app.labels" . | nindent 8 }}
        app: company
      annotations:
        "resource.opentelemetry.io/service.name": "company-service"
        "instrumentation.opentelemetry.io/inject-java": "true"
    spec:
      containers:
        - name: company
          image: "{{ .Values.repository }}/andreasgerner/distributed-tracing/sample-company:{{ .Values.company.imageTag | default .Values.defaultTag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: PAYMENT_URL
              value: "http://payment-service:8080"
            {{- if .Values.company.databaseUrl }}
            - name: DB_URL
              value: "{{ .Values.company.databaseUrl }}"
            {{- else }}
            - name: SPRING_PROFILES_ACTIVE
              value: "h2"
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
          resources:
            {{- toYaml .Values.company.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-company
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app: company
spec:
  ports:
    - port: {{ .Values.company.port }}
      name: http
      targetPort: http
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app: company
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample-app.fullname" . }}-company
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app: company
spec:
  ingressClassName: openshift-default
  tls:
    - hosts:
        - tracing-company.apps.ocp-test.cloud.nuernberger.net
      secretName: nv-default-cert
  rules:
    - host: tracing-company.apps.ocp-test.cloud.nuernberger.net
      http:
        paths:
          - backend:
              service:
                name: company-service
                port:
                  name: http
            pathType: ImplementationSpecific
