apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}-payment
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: payment
  template:
    metadata:
      labels:
        {{- include "sample-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: payment
      annotations:
        "instrumentation.opentelemetry.io/inject-java": "true"
    spec:
      containers:
        - name: payment
          image: "{{ .Values.imageRegistry }}/andreasgerner/distributed-tracing/sample-payment:{{ .Values.payment.imageTag | default .Values.defaultTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            {{- if .Values.payment.databaseUrl }}
            - name: DB_URL
              value: "{{ .Values.payment.databaseUrl }}"
            {{- else }}
            - name: SPRING_PROFILES_ACTIVE
              value: "h2"
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: http
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /actuator/health/liveness
              port: http
          resources:
            {{- toYaml .Values.payment.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-payment
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: payment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample-app.fullname" . }}-payment
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment
spec:
  {{- if .Values.payment.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.payment.ingress.host }}
      secretName: {{ .Values.payment.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.payment.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "sample-app.fullname" . }}-payment
                port:
                  name: http
            pathType: ImplementationSpecific
