apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        "resource.opentelemetry.io/service.name": "payment-service"
        "instrumentation.opentelemetry.io/inject-java": "true"
    spec:
      containers:
        - name: payment
          image: artifactory:5000/andreasgerner/distributed-tracing/sample-payment:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: h2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '128Mi'
            limits:
              memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: payment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-ingress
spec:
  ingressClassName: openshift-default
  tls:
    - hosts:
        - tracing-payment.apps.ocp-test.cloud.nuernberger.net
      secretName: nv-default-cert
  rules:
    - host: tracing-payment.apps.ocp-test.cloud.nuernberger.net
      http:
        paths:
          - backend:
              service:
                name: payment-service
                port:
                  name: http
            pathType: ImplementationSpecific
