apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}-angular
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: angular
  template:
    metadata:
      labels:
        {{- include "sample-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: angular
    spec:
      containers:
        - name: angular
          image: "{{ .Values.imageRegistry }}/andreasgerner/distributed-tracing/sample-web-angular:{{ .Values.angular.imageTag | default .Values.defaultTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
          resources:
            {{- toYaml .Values.angular.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-angular
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: angular
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: angular
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample-app.fullname" . }}-angular
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: angular
spec:
  {{- if .Values.angular.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.angular.ingress.host }}
      secretName: {{ .Values.angular.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.angular.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "sample-app.fullname" . }}-angular
                port:
                  name: http
            pathType: ImplementationSpecific
