apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-angular-deployment
  labels:
    app: web-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-angular
  template:
    metadata:
      labels:
        app: web-angular
    spec:
      containers:
        - name: web-angular
          image: artifactory:5000/andreasgerner/distributed-tracing/sample-web-angular:openshift
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-angular-service
  labels:
    app: web-angular
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: web-angular
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-angular-ingress
spec:
  ingressClassName: openshift-default
  tls:
    - hosts:
        - tracing-web-angular.apps.ocp-test.cloud.nuernberger.net
      secretName: nv-default-cert
  rules:
    - host: tracing-web-angular.apps.ocp-test.cloud.nuernberger.net
      http:
        paths:
          - backend:
              service:
                name: web-angular-service
                port:
                  name: http
            pathType: ImplementationSpecific
