apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}-next
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: next
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: next
  template:
    metadata:
      labels:
        {{- include "sample-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: next
      annotations:
        "instrumentation.opentelemetry.io/inject-nodejs": "true"
    spec:
      containers:
        - name: next
          image: "{{ .Values.imageRegistry }}/andreasgerner/distributed-tracing/sample-web-next:{{ .Values.next.imageTag | default .Values.defaultTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: COMPANY_URL
              value: "http://{{ include "sample-app.fullname" . }}-company:80"
            - name: PAYMENT_URL
              value: "http://{{ include "sample-app.fullname" . }}-payment:80"
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
          resources:
            {{- toYaml .Values.next.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-next
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: next
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: next
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample-app.fullname" . }}-next
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: next
spec:
  {{- if .Values.next.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.next.ingress.host }}
      secretName: {{ .Values.next.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.next.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "sample-app.fullname" . }}-next
                port:
                  name: http
            pathType: ImplementationSpecific
