apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-next-deployment
  labels:
    app: web-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-next
  template:
    metadata:
      labels:
        app: web-next
      annotations:
        "resource.opentelemetry.io/service.name": "web-next"
        "instrumentation.opentelemetry.io/inject-nodejs": "true"
    spec:
      containers:
        - name: web-next
          image: artifactory:5000/andreasgerner/distributed-tracing/sample-web-next:latest
          imagePullPolicy: Always
          env:
            - name: COMPANY_URL
              value: "http://company-service:8080"
            - name: PAYMENT_URL
              value: "http://payment-service:8080"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-next-service
  labels:
    app: web-next
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: web-next
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-next-ingress
spec:
  ingressClassName: openshift-default
  tls:
    - hosts:
        - tracing-web-next.apps.ocp-test.cloud.nuernberger.net
      secretName: nv-default-cert
  rules:
    - host: tracing-web-next.apps.ocp-test.cloud.nuernberger.net
      http:
        paths:
          - backend:
              service:
                name: web-next-service
                port:
                  name: http
            pathType: ImplementationSpecific
