apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tracing.fullname" . }}
  labels:
    {{- include "tracing.labels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
    - from:
        - ipBlock:
            cidr: 172.16.0.0/12
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 4318
        - protocol: TCP
          port: 16686
  policyTypes:
    - Ingress
