apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "tracing.fullname" . }}-opentelemetry
  labels:
    {{- include "tracing.labels" . | nindent 4 }}
spec:
  managementState: managed
  {{- if .Values.opentelemetryCollector.autoscaling.enabled }}
  autoscaler:
      minReplicas: {{ .Values.opentelemetryCollector.autoscaling.minReplicas }}
      maxReplicas: {{ .Values.opentelemetryCollector.autoscaling.maxReplicas }}
      targetCPUUtilization: {{ .Values.opentelemetryCollector.autoscaling.targetCPU }}
      targetMemoryUtilization: {{ .Values.opentelemetryCollector.autoscaling.targetMemory }}
  {{- end }}
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      otlp:
        endpoint: "http://{{ include "tracing.fullname" . }}-jaeger-collector.{{ .Release.Namespace }}.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
