apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "tracing.fullname" . }}
  labels:
    {{- include "tracing.labels" . | nindent 4 }}
spec:
  env:
    - name: OTEL_METRICS_EXPORTER
      value: none
    - name: OTEL_LOGS_EXPORTER
      value: none
  exporter:
    # grpc endpoint
    endpoint: http://{{ include "tracing.fullname" . }}-opentelemetry-collector.{{ .Release.Namespace }}.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  resource:
    addK8sUIDAttributes: true
  java:
    {{- if .Values.global.imageRegistry }}
    image: "{{ .Values.global.imageRegistry }}/open-telemetry/opentelemetry-operator/autoinstrumentation-java:{{ .Values.instrumentation.java.imageTag | default .Values.defaultTag }}"
    {{- end }}
    env:
      # java uses http exporter by default, so change endpoint to http
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://{{ include "tracing.fullname" . }}-opentelemetry-collector.{{ .Release.Namespace }}.svc.cluster.local:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
  nodejs:
    {{- if .Values.global.imageRegistry }}
    image: "{{ .Values.global.imageRegistry }}/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:{{ .Values.instrumentation.nodejs.imageTag | default .Values.defaultTag }}"
    {{- end }}
