global:
  imageRegistry:

nameOverride: ""
fullnameOverride: "tracing"

defaultTag: "latest"
imagePullPolicy: "IfNotPresent"

opentelemetryCollector:
  autoscaling:
    enabled: false
    minReplicas:
    maxReplicas:
    targetCPU:
    targetMemory:

opentelemetryProxy:
  imageTag: "alpine"
  resources: {}
  cors:
    allowedOrigin: ""
  autoscaling:
    enabled: false
    minReplicas:
    maxReplicas:
    targetCPU:
    targetMemory:
  ingress:
    tls:
      enabled: false
      secretName: ""
    host: ""

instrumentation:
  java:
    imageTag: ""
  nodejs:
    imageTag: ""


elasticsearch:
  fullnameOverride: tracing-elasticsearch
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  security:
    elasticPassword: j43g3r2024
  sysctlImage:
    enabled: false

jaeger:
  fullnameOverride: tracing-jaeger
  provisionDataStore:
    cassandra: false

  storage:
    type: elasticsearch
    elasticsearch:
      host: tracing-elasticsearch
      port: 9200
      scheme: http
      user: elastic
      password: j43g3r2024

  query:
    service:
      targetPort: 16686
    ingress: {}

  collector:
    service:
      otlp:
        grpc:
          name: otlp-grpc
          port: 4317

