global:
  imageRegistry:

nameOverride: ""
fullnameOverride: "tracing"

defaultTag: "latest"
imagePullPolicy: "IfNotPresent"

opentelemetryProxy:
  imageTag: "alpine"
  resources: {}
  cors:
    allowedOrigin: ""
  ingress:
    tls:
      enabled: false
      secretName: ""
    host: ""

instrumentation:
  java:
    imageTag: ""
  nodejs:
    imageTag: ""


elasticsearch:
  fullnameOverride: tracing-elasticsearch
  master:
    masterOnly: false
    replicaCount: 1
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      privileged: false
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 250m
        memory: 768Mi
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  security:
    elasticPassword: j43g3r2024
  sysctlImage:
    enabled: false

jaeger:
  fullnameOverride: tracing-jaeger
  provisionDataStore:
    cassandra: false

  storage:
    type: elasticsearch
    elasticsearch:
      host: tracing-elasticsearch
      port: 9200
      scheme: http
      user: elastic
      password: j43g3r2024

  query:
    service:
      targetPort: 16686
    ingress: {}

  collector:
    service:
      otlp:
        grpc:
          name: otlp-grpc
          port: 4317
        http:
          name: otlp-http
          port: 4138
